//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TnCode.TnCodeApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TnCode.TnCodeApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Aesthetic Name=&quot;bar&quot;&gt;
        ///  &lt;AestheticValues&gt;
        ///    &lt;AestheticValue Name=&quot;X&quot; Required=&quot;true&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Y&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Alpha&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Colour&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Fill&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Group&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;LineType&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Size&quot;/&gt;
        ///  &lt;/AestheticValues&gt;
        ///  &lt;DefaultStat&gt;Count&lt;/DefaultStat&gt;
        ///  &lt;DefaultPosition&gt;Stack&lt;/DefaultPosition&gt;
        ///  &lt;Values&gt;
        ///    &lt;Property  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string geom_bar {
            get {
                return ResourceManager.GetString("geom_bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Aesthetic Name=&quot;tile&quot;&gt;
        ///  &lt;AestheticValues&gt;
        ///    &lt;AestheticValue Name=&quot;X&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Y&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Fill&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Group&quot;/&gt;
        ///  &lt;/AestheticValues&gt;
        ///  &lt;DefaultStat&gt;Bin2d&lt;/DefaultStat&gt;
        ///  &lt;DefaultPosition&gt;Identity&lt;/DefaultPosition&gt;
        ///&lt;/Aesthetic&gt;.
        /// </summary>
        public static string geom_bin2d {
            get {
                return ResourceManager.GetString("geom_bin2d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Aesthetic Name=&quot;boxplot&quot;&gt;
        ///  &lt;AestheticValues&gt;
        ///    &lt;AestheticValue Name=&quot;X&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Y&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Alpha&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Colour&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Fill&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Group&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Shape&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Size&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Weight&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;LineType&quot;/&gt;
        ///  &lt;/AestheticValues&gt;
        ///  &lt;DefaultStat&gt;Boxplot&lt;/DefaultStat&gt;
        ///  &lt;Defa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string geom_boxplot {
            get {
                return ResourceManager.GetString("geom_boxplot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Aesthetic Name=&quot;bar&quot;&gt;
        ///  &lt;AestheticValues&gt;
        ///    &lt;AestheticValue Name=&quot;X&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Y&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Alpha&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Colour&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Size&quot;/&gt;
        ///  &lt;/AestheticValues&gt;
        ///  &lt;DefaultStat&gt;Contour&lt;/DefaultStat&gt;
        ///  &lt;DefaultPosition&gt;Identity&lt;/DefaultPosition&gt;
        ///  &lt;Properties&gt;
        ///    &lt;Property Tag=&quot;Line End&quot; Name=&quot;lineend&quot; Value=&quot;&quot;&gt;
        ///      &lt;Options&gt;
        ///        &lt;Option Name=&quot;Round&quot; Value=&quot;round&quot;/&gt;
        ///        &lt;Opti [rest of string was truncated]&quot;;.
        /// </summary>
        public static string geom_contour {
            get {
                return ResourceManager.GetString("geom_contour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Aesthetic Name=&quot;density&quot;&gt;
        ///  &lt;AestheticValues&gt;
        ///    &lt;AestheticValue Name=&quot;X&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Y&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Alpha&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Colour&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Fill&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Group&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Size&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Weight&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;LineType&quot;/&gt;
        ///  &lt;/AestheticValues&gt;
        ///  &lt;DefaultStat&gt;Density&lt;/DefaultStat&gt;
        ///  &lt;DefaultPosition&gt;Identity&lt;/DefaultPositio [rest of string was truncated]&quot;;.
        /// </summary>
        public static string geom_density {
            get {
                return ResourceManager.GetString("geom_density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Aesthetic Name=&quot;density_2d&quot;&gt;
        ///  &lt;AestheticValues&gt;
        ///    &lt;AestheticValue Name=&quot;X&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Y&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Alpha&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Colour&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Group&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;LineType&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Size&quot;/&gt;
        ///  &lt;/AestheticValues&gt;
        ///  &lt;DefaultStat&gt;Density_2d&lt;/DefaultStat&gt;
        ///  &lt;DefaultPosition&gt;Identity&lt;/DefaultPosition&gt;
        ///  &lt;Properties&gt;
        ///    &lt;Property Tag=&quot;Line End&quot; Name=&quot;lineend&quot; Va [rest of string was truncated]&quot;;.
        /// </summary>
        public static string geom_density_2d {
            get {
                return ResourceManager.GetString("geom_density_2d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Aesthetic Name=&quot;Dotplot&quot;&gt;
        ///  &lt;AestheticValues&gt;
        ///    &lt;AestheticValue Name=&quot;X&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Y&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Alpha&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Colour&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Fill&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Group&quot;/&gt;
        ///  &lt;/AestheticValues&gt;
        ///  &lt;DefaultStat&gt;Bindot&lt;/DefaultStat&gt;
        ///  &lt;DefaultPosition&gt;Identity&lt;/DefaultPosition&gt;
        ///  &lt;Properties&gt;
        ///    &lt;Property Tag=&quot;Bin Axis&quot; Name=&quot;binaxis&quot; Value=&quot;&quot;&gt;
        ///      &lt;Options&gt;
        ///        &lt;Option Name [rest of string was truncated]&quot;;.
        /// </summary>
        public static string geom_dotplot {
            get {
                return ResourceManager.GetString("geom_dotplot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Aesthetic Name=&quot;errorbar&quot;&gt;
        ///  &lt;AestheticValues&gt;
        ///    &lt;AestheticValue Name=&quot;X&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;YMin&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;YMax&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Alpha&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Colour&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Group&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Height&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;LineType&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Size&quot;/&gt;
        ///  &lt;/AestheticValues&gt;
        ///  &lt;DefaultStat&gt;Identity&lt;/DefaultStat&gt;
        ///  &lt;DefaultPosition&gt;Identity&lt;/DefaultPo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string geom_errorbar {
            get {
                return ResourceManager.GetString("geom_errorbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Aesthetic Name=&quot;hex&quot;&gt;
        ///  &lt;AestheticValues&gt;
        ///    &lt;AestheticValue Name=&quot;X&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Y&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Alpha&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Colour&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Fill&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Group&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Size&quot;/&gt;
        ///  &lt;/AestheticValues&gt;
        ///  &lt;DefaultStat&gt;Binhex&lt;/DefaultStat&gt;
        ///  &lt;DefaultPosition&gt;Identity&lt;/DefaultPosition&gt;
        ///&lt;/Aesthetic&gt;.
        /// </summary>
        public static string geom_hex {
            get {
                return ResourceManager.GetString("geom_hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Aesthetic Name=&quot;bar&quot;&gt;
        ///  &lt;AestheticValues&gt;
        ///    &lt;AestheticValue Name=&quot;X&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Y&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Alpha&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Colour&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Fill&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Group&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;LineType&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Size&quot;/&gt;
        ///  &lt;/AestheticValues&gt;
        ///  &lt;DefaultStat&gt;Bin&lt;/DefaultStat&gt;
        ///  &lt;DefaultPosition&gt;Identity&lt;/DefaultPosition&gt;
        ///  &lt;Values&gt;
        ///    &lt;Property Tag=&quot;Bin Width&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string geom_histogram {
            get {
                return ResourceManager.GetString("geom_histogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Aesthetic Name=&quot;line&quot;&gt;
        ///  &lt;AestheticValues&gt;
        ///    &lt;AestheticValue Name=&quot;X&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Y&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Alpha&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Colour&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Group&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;LineType&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Size&quot;/&gt;
        ///  &lt;/AestheticValues&gt;
        ///  &lt;DefaultStat&gt;Identity&lt;/DefaultStat&gt;
        ///  &lt;DefaultPosition&gt;Identity&lt;/DefaultPosition&gt;
        ///  &lt;Properties&gt;
        ///    &lt;Property Tag=&quot;Line End&quot; Name=&quot;lineend&quot; Value=&quot;&quot;&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string geom_line {
            get {
                return ResourceManager.GetString("geom_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Aesthetic Name=&quot;point&quot;&gt;
        ///  &lt;AestheticValues&gt;
        ///    &lt;AestheticValue Name=&quot;X&quot; Required=&quot;true&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Y&quot; Required=&quot;true&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Alpha&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Colour&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Fill&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Group&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Shape&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Size&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Stroke&quot;/&gt;
        ///  &lt;/AestheticValues&gt;
        ///  &lt;DefaultStat&gt;Identity&lt;/DefaultStat&gt;
        ///  &lt;DefaultPosit [rest of string was truncated]&quot;;.
        /// </summary>
        public static string geom_point {
            get {
                return ResourceManager.GetString("geom_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Aesthetic Name=&quot;quantile&quot;&gt;
        ///  &lt;AestheticValues&gt;
        ///    &lt;AestheticValue Name=&quot;X&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Y&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Alpha&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Colour&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Group&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;LineType&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Size&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Weight&quot;/&gt;
        ///  &lt;/AestheticValues&gt;
        ///  &lt;DefaultStat&gt;Quantile&lt;/DefaultStat&gt;
        ///  &lt;DefaultPosition&gt;Identity&lt;/DefaultPosition&gt;
        ///&lt;/Aesthetic&gt;.
        /// </summary>
        public static string geom_quantile {
            get {
                return ResourceManager.GetString("geom_quantile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Aesthetic Name=&quot;rug&quot;&gt;
        ///  &lt;AestheticValues&gt;
        ///    &lt;AestheticValue Name=&quot;X&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Y&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Alpha&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Colour&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Group&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Size&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Linetype&quot;/&gt;
        ///  &lt;/AestheticValues&gt;
        ///  &lt;DefaultStat&gt;Identity&lt;/DefaultStat&gt;
        ///  &lt;DefaultPosition&gt;Identity&lt;/DefaultPosition&gt;
        ///  &lt;Properties&gt;
        ///    &lt;Property Tag=&quot;Sides&quot; Name=&quot;sides&quot; Value=&quot;bl&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string geom_rug {
            get {
                return ResourceManager.GetString("geom_rug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Aesthetic Name=&quot;smooth&quot;&gt;
        ///  &lt;AestheticValues&gt;
        ///    &lt;AestheticValue Name=&quot;X&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Y&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Alpha&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Colour&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Fill&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Group&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;LineType&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Size&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Weight&quot;/&gt;
        ///  &lt;/AestheticValues&gt;
        ///  &lt;DefaultStat&gt;Smooth&lt;/DefaultStat&gt;
        ///  &lt;DefaultPosition&gt;Identity&lt;/DefaultPosition&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string geom_smooth {
            get {
                return ResourceManager.GetString("geom_smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Aesthetic Name=&quot;violin&quot;&gt;
        ///  &lt;AestheticValues&gt;
        ///    &lt;AestheticValue Name=&quot;X&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Y&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Alpha&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Colour&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Fill&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Group&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;LineType&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Size&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Weight&quot;/&gt;
        ///  &lt;/AestheticValues&gt;
        ///  &lt;DefaultStat&gt;Ydensity&lt;/DefaultStat&gt;
        ///  &lt;DefaultPosition&gt;Dodge&lt;/DefaultPosition&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string geom_violin {
            get {
                return ResourceManager.GetString("geom_violin", resourceCulture);
            }
        }
    }
}
