using System.Collections.Generic;

namespace SharpStatistics.EasyERAddIn.Functions.Controls
{
    public interface IFunctionControl
    {
        string VariableName{ get; set; }

        /// <summary>
        /// The R Code 
        /// </summary>
        /// <returns>R code that is generated by the control</returns>
        string GetRCode();

        void SetValues(List<object> newValues);

        bool IsValid { get; set; }

        /// <summary>
        /// Indicate if all occurances of the variabel name should be replaced or just the first one.
        /// </summary>
        bool ReplaceAll { get; set; }
    }
}
