//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleR.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModuleR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;LayerProperties Name=&quot;point&quot;&gt;
        ///  &lt;AestheticValues&gt;
        ///    &lt;AestheticValue Name=&quot;XVariable&quot; Required=&quot;true&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;YVariable&quot; Required=&quot;true&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Alpha&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Colour&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Fill&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Group&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Shape&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Size&quot;/&gt;
        ///    &lt;AestheticValue Name=&quot;Stroke&quot;/&gt;
        ///  &lt;/AestheticValues&gt;
        ///  &lt;Stat&gt;Identity&lt;/Stat&gt;
        ///  &lt;Posi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string geom_point {
            get {
                return ResourceManager.GetString("geom_point", resourceCulture);
            }
        }
    }
}
